export default [
	{
		name: 'CizeNet',
		directory: 'cizenet',
		description: 'A forum theme made for the CizeNet community.',
		date: 'November 2014',
		frameworks: ['Invision Power Board 3.4'],
		languages: ['HTML', 'CSS', 'JavaScript', 'PHP'],
	},
	{
		name: 'Divulga Eng',
		directory: 'divulga-eng',
		description: 'A Laravel app made for Divulga Eng, a portal to bring together engineers and partners to provide them with easy access to spreadsheets, engineering and construction courses, a partners discounts card, personal opportunities, engineering innovations, and more.',
		date: 'February - June 2017',
		frameworks: ['Laravel 5.4'],
		languages: ['HTML', 'CSS', 'JavaScript', 'PHP'],
	},
	{
		name: 'Forum Hour',
		directory: 'forum-hour',
		description: 'A forum theme made for the Forum Hour community.',
		date: 'October 2013',
		frameworks: ['Invision Power Board 3.4'],
		languages: ['HTML', 'CSS', 'JavaScript', 'PHP'],
	},
	{
		name: 'MvPxC',
		directory: 'mvpxc',
		description: 'A forum theme made for the MvPxC community.',
		date: 'November 2014',
		frameworks: ['MyBB 1.8'],
		languages: ['HTML', 'CSS', 'JavaScript', 'PHP', 'SQL'],
	},
	{
		name: 'Nordeste Portas',
		directory: 'nordeste-portas',
		description: 'A fully-custom PHP app made for Nordeste Portas to showcase their company, products, and services, among other entities.',
		date: 2017,
		languages: ['HTML', 'CSS', 'JavaScript', 'PHP', 'SQL'],
	},
	{
		name: 'Nulled',
		directory: 'nulled',
		description: 'A forum theme made for the Nulled community.',
		date: 2014,
		frameworks: ['Invision Power Board 3.4'],
		languages: ['HTML', 'CSS', 'JavaScript', 'PHP'],
	},
	{
		name: 'Palette Town',
		directory: 'palette-town',
		description: 'A forum theme made for the Lake Valor community. Includes many extensive features such as a background changer, color scheme changer, width changer, forum thread style preferences, and more.',
		date: '2016 - 2017',
		frameworks: ['Invision Power Board 3.4'],
		languages: ['HTML', 'CSS', 'JavaScript', 'PHP', 'SQL'],
	},
	{
		name: 'Vue Discord Message',
		directory: 'vue-discord-message',
		description: 'Vue components to easily build and display fake Discord messages on your webpages.',
		repo: 'Danktuary/vue-discord-message',
		site: 'https://vue-discord-message.netlify.com/',
		date: '2018 -2019',
		frameworks: ['Vue'],
		languages: ['HTML', 'CSS', 'JavaScript'],
	},
];
